---
# tasks file for ansidocks
- name: Create directory
  ansible.builtin.file:
    path: ./containers/
    state: directory
    mode: "0775"

- name: Create Containers directory
  ansible.builtin.file:
    path: ./containers/{{ item.container_name }}
    state: directory
    mode: "0775"
  loop: "{{ containers }}"
  register: containers_folders
  loop_control:
    label: "Creating directory on ./containers/ {{ item.container_name }}"

- name: Create Data directory
  ansible.builtin.file:
    path: ./containers/{{ item.container_name }}/data/
    state: directory
    mode: "0775"
  loop: "{{ containers }}"
  loop_control:
    label: "Creating directory on ./containers/{{ item.container_name }}/data/"

- name: Create Log directory
  ansible.builtin.file:
    path: ./containers/{{ item.container_name }}/log/
    state: directory
    mode: "0775"
  loop: "{{ containers }}"
  loop_control:
    label: "Creating directory on ./containers/{{ item.container_name }}/log/"

- name: Fixing user permissions
  ansible.builtin.shell: |
    chown -R kontrol:kontrol ./containers/
  register: output_chown
  changed_when: output_chown.rc == 0

- name: Copy DockerFiles from source
  ansible.builtin.copy:
    src: files/dockerfiles/{{ item.container_name }}/Dockerfile
    dest: ./containers/{{ item.container_name }}/Dockerfile
    mode: "0775"
  loop: "{{ containers }}"
  loop_control:
    label: "Copying Dockerfile to ./containers/{{ item.container_name }}/Dockerfile"
